Add Scala v2.13 support, drop Scala v2.11
### Dealing with scala.Seq becoming scala.collection.immutable.Seq

From https://docs.scala-lang.org/overviews/core/collections-migration-213.html#scalaseq-varargs-and-scalaindexedseq-migration

> `scala.Seq[+A]` is now an alias for `scala.collection.immutable.Seq[A]`
> (instead of `scala.collection.Seq[A]`)

This change occurred with commit 457dfd07449a8b7943b2a6c614fb57ea2a7b452e
in https://github.com/scala/scala/pull/6498 - it led to
difficult-to-comprehend compilation errors for Marley with Scala 2.13:

```
[info] Compiling 1 Scala source to /home/roberto/guardian/marley/core/target/scala-2.13/test-classes ...
[error] /home/roberto/guardian/marley/core/src/test/scala/com/gu/marley/AvroFileSpec.scala:47:55: Expected the companion object of scala.collection.Seq[String] to have an 'apply' method
[error]       implicit val structSer = AvroSerialisable.struct[ExampleStruct]
[error]                                                       ^
[error] /home/roberto/guardian/marley/core/src/test/scala/com/gu/marley/AvroFileSpec.scala:54:35: Expected the companion object of scala.collection.Seq[String] to have an 'apply' method
[error]       AvroFile.read[ExampleStruct](file).head == struct
[error]                                   ^
[error] two errors found
[error] (core / Test / compileIncremental) Compilation failed
```

The error is saying "Expected the companion object of
`scala.collection.Seq[String]` to have an 'apply' method" because the
`AvroSerialisableMacro.implicitFor(typ: c.universe.Type)` method wasn't
able to match `scala.collection.Seq[String]` using the
`subTypeOf(typ, seqType)` when `seqType = typeOf[scala.Seq[_]]` - which
in Scala 2.13 equals `typeOf[scala.collection.immutable.Seq[_]]`:

https://github.com/guardian/marley/blob/849eae4d49895b169e53a9eb2ec7f565c544461c/core/src/main/scala/com/gu/marley/AvroSerialisable.scala#L278-L288

As `scala.collection.Seq[String]` *isn't* a subtype of
`scala.collection.immutable.Seq[String]` - it's a supertype - there's no
match found and things-go-wrong.

Given a `list<string>` thrift field, Scrooge v19.2.0 and above generate
a Scala field of type `scala.collection.Seq[String]`...

https://github.com/twitter/scrooge/blob/2324adba195e43232e406fe83ec6598a0d09d43c/scrooge-generator/src/main/scala/com/twitter/scrooge/backend/ScalaGenerator.scala#L222-L224
https://contributors.scala-lang.org/t/experience-of-migrating-to-2-13-x/3367

...so we _have_ to ensure that our `implicitFor()` method can match against
`scala.collection.Seq[String]`. Essentially the scrooge plugin, and we,
in this change, are adopting "Option 1: migrate back to
scala.collection.Seq" from the Scala 2.13 migration guide on this topic:

https://docs.scala-lang.org/overviews/core/collections-migration-213.html#option-1-migrate-back-to-scalacollectionseq

See also:

https://www.scala-lang.org/blog/2017/02/28/collections-rework.html#language-integration
http://eed3si9n.com/masking-scala-seq

##### How did I debug this issue?

I've never written any Scala macros, so how did I debug this issue?
Basically tonnes of printlns in the `AvroSerialisable` code, comparing
the output when running Scala 2.12 vs 2.13. That showed me there was a
divergence, but it was too noisy to really spot the problem. All I could
really see was that `optListString: _root_.scala.Option[_root_.scala.collection.Seq[String]]`
was the field that was the problem.

Eventually I attached a debugger (see https://stackoverflow.com/a/15505308/438886)
and set a breakpoint in the code on the line reporting the error:

https://github.com/guardian/marley/blob/849eae4d49895b169e53a9eb2ec7f565c544461c/core/src/main/scala/com/gu/marley/AvroSerialisable.scala#L270

...once the breakpoint was hit (it was only hit in Scala 2.13, not Scala
2.12), I looked back up the stacktrace, and set another breakpoint further
up the code here:

https://github.com/guardian/marley/blob/849eae4d49895b169e53a9eb2ec7f565c544461c/core/src/main/scala/com/gu/marley/AvroSerialisable.scala#L161

...but this time with a breakpoint condition so it only suspended for the
particular field that was causing a problem:

```
typ.toString=="com.gu.marley.ExampleStruct" &&
 apply.toString=="method apply" &&
 termName.toString=="optListString"
```

...this breakpoint was hit for both Scala v2.13 & v2.12, so from there I
could carefully step forward into the `implicitFor()` method, and see
that the code diverged on this line:

https://github.com/guardian/marley/blob/849eae4d49895b169e53a9eb2ec7f565c544461c/core/src/main/scala/com/gu/marley/AvroSerialisable.scala#L287

...which - after carefully study of the types, and examining `seqType`,
finally led to me understanding the issue.

### Drop Scala 2.11 support

Scala 2.11 gives a compilation error when attempting to cross-compile with
it, and it's no longer worth the effort of trying to find the cause.

### Another change for Scala <-> Java collection conversion

`scala.collection.convert.decorateAsJava` (introduced in Scala 2.8.1) is
gone, switching to `scala.collection.JavaConverters` (also introduced in
Scala 2.8.1?) although that _has_ been deprecated, apparently for
`scala.jdk.CollectionConverters` in Scala 2.13.0 - we can switch over when
we drop Scala 2.12 support.